server:
  port: 8811

spring:
  datasource:
    url: jdbc:mysql://10.4.92.144:3306/star?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver