# spring profile  上线前需手动指定
spring:
  profiles:
    active: local
#mybatis配置
mybatis:
#  typeAliasesPackage: com.example.mybaitsxml.dao.entity
  mapperLocations: classpath:mapper/sys/*.xml
  #configLocation: classpath:/mybatis-config.xml
